version: "3.4"

services:
  # client:
  #   image: nginx-client
  #   build:
  #     context: .
  #     target: nginx-client
  #   restart: always
  #   ports:
  #     - 3080:80
  #   volumes:
  #     - /client/node_modules
  #   depends_on:
  #     - api
  api:
    ports:
      - 80:3080               # Change it to 9000:3080 if you want to use nginx
    depends_on:
      - mongodb
    image: node-api
    build:
      context: .
      target: node-api
    restart: always
    env_file:
      - ./api/.env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/chatgpt-clone
      # - CHATGPT_REVERSE_PROXY=http://host.docker.internal:8080/api/conversation # if you are hosting your own chatgpt reverse proxy
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_HTTP_ADDR=meilisearch:7700
    volumes:
      - ${WEBAPP_STORAGE_HOME}/client/node_modules:/client/node_modules
      - ${WEBAPP_STORAGE_HOME}/api:/api
      - ${WEBAPP_STORAGE_HOME}/api/node_modules:/api/node_modules
  mongodb:
    ports:
      - 27018:27017
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ${WEBAPP_STORAGE_HOME}/data-node:/data/db
    command: mongod --noauth
  meilisearch:
    image: getmeili/meilisearch:v1.0
    ports:
      - 7700:7700
    env_file:
      - ./api/.env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_HTTP_ADDR=meilisearch:7700
    volumes:
      - ${WEBAPP_STORAGE_HOME}/meili_data:/meili_data
